#!/usr/bin/env sh
# ====== Variables =============================

gaps_top="20"
gaps_bottom="20"
gaps_left="15"
gaps_right="15"
gaps_inner="25"

normal_border_color="010101"
focused_border_color="6699cc"
preselect_border_color="d75f5f"

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap

yabai -m config window_opacity              off
yabai -m config window_shadow               off
yabai -m config window_placement            second_child

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       1.0
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                on

# ====== List of rules =========================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Surge 3" app="^Surge 3$" manage=off
yabai -m rule --add label="Surge Dashboard" app="^Surge Dashboard$" manage=off
yabai -m rule --add label="Fantastical" app="^Fantastical$" manage=off
yabai -m rule --add label="Calendar" app="^Calendar$" manage=off
yabai -m rule --add label="Drafts" app="^Drafts$" manage=off
yabai -m rule --add label="Tweetbot" app="^Tweetbot$" manage=off
yabai -m rule --add label="DaisyDisk" app="^DaisyDisk$" manage=off
yabai -m rule --add label="Amazon Chime" app="^Amazon Chime$" manage=off
yabai -m rule --add label="Alfred Preferences" app="^Alfred Preferences$" manage=off
yabai -m rule --add label="Microsoft Outlook" app="^Microsoft Outlook$" manage=off
yabai -m rule --add label="Cisco AnyConnect Secure Mobility Client" app="^Cisco AnyConnect Secure Mobility Client$" manage=off
yabai -m rule --add label="Tor Browser" app="^Tor Browser$" manage=off
yabai -m rule --add label="Slack" app="^Slack$" manage=off
yabai -m rule --add label="Bitwarden" app="^Bitwarden$" manage=off
yabai -m rule --add label="Steam" app="^Steam$" manage=off
yabai -m rule --add label="Civilization VI" app="^Civilization VI$" manage=off
yabai -m rule --add label="Simulator" app="^Simulator$" manage=off
